version: '3.8'

services:
  payload:
    image: node:18-buster
    command: sh -c "npm install && npm run dev"
    working_dir: /home/node/app/
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017/payload}
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET:-mysecret}
      PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL:-http://localhost:3000}
      HOSTNAME: ${HOSTNAME:-localhost}
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
  node_modules: