version: '3'

services:

  payload:
    image: node:18-alpine
    expose:
      - 3000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.payload.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.payload.tls.certresolver=myresolver
      - traefik.http.routers.payload.service=payload
      - traefik.http.services.payload.loadbalancer.server.port=3000
    env_file:
      - stack.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
      PAYLOAD_PUBLIC_SERVER_URL:
      HOSTNAME:
    networks:
      - traefik
      - backend

  mongo:
    image: mongo:latest
    expose:
      - 27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - backend

volumes:
  data:
  node_modules:

networks:
  backend:
  traefik:
    external: true