version: '3.8'

services:
  payload:
    image: node:18-buster
    command: sh -c "npm install && npm run dev"
    working_dir: /home/node/app/
    environment:
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017/payload}
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET:-mysecret}
      PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL:-http://localhost:3000}
      HOSTNAME: ${HOSTNAME:-localhost}
    volumes:
      - node_modules:/home/node/app/node_modules
      - ./:/home/node/app
    networks:
      - traefik
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.payload.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.payload.tls.certresolver=myresolver
      - traefik.http.routers.payload.service=payload
      - traefik.http.services.payload.loadbalancer.server.port=3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    networks:
      - backend

volumes:
  data:
  node_modules:

networks:
  backend:
  traefik:
    external: true
